environment: staging

gcp:
  projectId: beyond-chat-1111
  region: europe-west3

domains:
  app: staging.chat.beyondtheloop.ai
  mcp: mcp-m365-staging.beyondtheloop.ai
  redirectFrom: staging.v2.beyondtheloop.ai

serviceAccount:
  gcpServiceAccount: bchat-app-staging@beyond-chat-1111.iam.gserviceaccount.com

gateway:
  staticIpName: bchat-staging-ingress-ip

cloudArmor:
  policyName: ""  # disabled in staging

observability:
  podMonitoring:
    enabled: true
