environment: prod

gcp:
  projectId: beyond-chat-1111
  region: europe-west3

domains:
  app: chat.beyondtheloop.ai
  mcp: mcp-m365.beyondtheloop.ai
  redirectFrom: v2.beyondtheloop.ai

serviceAccount:
  gcpServiceAccount: bchat-app-prod@beyond-chat-1111.iam.gserviceaccount.com

gateway:
  staticIpName: bchat-prod-ingress-ip

cloudArmor:
  policyName: bchat-prod-armor
