version: '3.8'

services:
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-v1.61.7
    environment:
      - "AZURE_OPENAI_API_BASE_URL=${AZURE_OPENAI_API_BASE_URL}"
      - "AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}"
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    extra_hosts:
      - host.docker.internal:host-gateway

  beyond-the-loop:
    image: ghcr.io/philszalay/beyond-the-loop:main
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #  args:
    #    LITELLM_BASE_URL: '/litellm'
    container_name: beyond-the-loop
    volumes:
      - ./backend/data:/app/backend/data
    depends_on:
      - litellm
    ports:
      - "8080:8080"  # Open Web UI port
    environment:
      - "OPENAI_API_BASE_URL=http://litellm:4000/v1"  # Point Open Web UI to LiteLLM
      - "DATABASE_URL=sqlite:////app/backend/data/database.sqlite"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  beyond-the-loop: {}
  litellm: {}
