"""
Auto-generated by scripts/generate_petrofer_mapping.py — DO NOT EDIT BY HAND.

Hardcoded Petrofer email→group mapping used at signup and backfill time.
"""

PETROFER_COMPANY_ID = "383e3338-9883-4b3e-8dd6-d32f9a58339f"

EMAIL_TO_GROUP_IDS: dict[str, list[str]] = {
    "alexander.byczkowicz@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
    ],
    "alexander.pott@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "ali.siala@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "alice.friedrich@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "30e5d414-3ca8-4dfb-8201-a8a562e3a98c",  # Finanzen
    ],
    "alkan.solak@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "019069a9-556a-4831-9ffb-76a502f47d49",  # F&E 1 Gießereitechnik
    ],
    "andre.koenig@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "andre.weber@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "andreas.hafke@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "andreas.klingenberg@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "8f3a70d1-bd62-4feb-9b56-69103a5ab7ad",  # Leitung Produktion und Logistik
    ],
    "andreas.niesporek@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "andreas.scharf@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "59c37098-5649-4b64-99e8-d7efc07e074d",  # Region Nord-Ost
    ],
    "andreas.schoener@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4773b7db-e4f9-4160-84be-2f06ee7b9937",  # Region Süd
    ],
    "anika.dybiona@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "anja.schubert@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "anke.friedrici@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
        "926c643a-ea69-445f-84a1-bfb5e045198e",  # Leitung F&E 2 Wärmebehandlung
    ],
    "annette.bleckmann@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
    ],
    "antje.neugebauer@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
    ],
    "artur.kawohl@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "astrid.schrot@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "axel.hoffmann@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "babette.petzold@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "birgit.duerkop@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "bjoern.knurr@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4773b7db-e4f9-4160-84be-2f06ee7b9937",  # Region Süd
    ],
    "burak.arsu@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "carola.schmalz@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
    ],
    "carsten.muehl@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "95327fd8-f5d4-4b00-81d9-9dd87fe9b869",  # Leitung Forschung und Entwicklung
    ],
    "catrin.saffran-wagenleiter@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
    ],
    "charis.wiesbaum@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f4e83e06-a218-45c7-8a86-575c76198915",  # Sicherheitsdatentechnik
    ],
    "christian.holzminden@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "2ce5e832-9292-424b-bc96-a6c3f29767f9",  # Leitung Vertrieb Metalworking Europe
    ],
    "christiana.schulz@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "christoph.klinkowski-buehring@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "019069a9-556a-4831-9ffb-76a502f47d49",  # F&E 1 Gießereitechnik
        "b3a0d087-7b05-4f2a-8ade-6e9ca547da92",  # Leitung F&E 1 Gießereitechnik
    ],
    "christoph.meister@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
        "76eca97a-84ae-4a15-8910-efeb8eec78a4",  # Leitung F&E 4 Zerspanung und Umformung
    ],
    "christoph.sachse@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
    ],
    "christoph.siegert@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "christopher.schulla@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "claudia.bolik@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "claudia.braune-krickau@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
    ],
    "constantin.fischer@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "975e8d9a-7a31-4bcd-b4a7-7c1a230a4299",  # Leitung Geschäftsführung CEO
    ],
    "daniel.wehrmaker@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
    ],
    "david.roda@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "davor.djekic@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "denis.kraft@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
    ],
    "dennis.habi@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
    ],
    "dennis.krasson@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "dennis.maslakov@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "dennis.schuetze@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "dennis.stoffregen@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
    ],
    "dieter.seipp@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "domenic-rene.sandvoss@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
    ],
    "dragan.djurdjevic@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "evelina.harder@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "evelyn.labat@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
    ],
    "fabian.keck@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "felix.goebel@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "filiz.odaci@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
    ],
    "finn.blumberg@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "15f7da41-c840-4fac-b403-701bc12742ad",  # Marketing
    ],
    "fischer-equity@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
    ],
    "florian.klassen@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
        "83805a32-2e65-4cf6-8308-f448d323bc77",  # Leitung Anwendungstechnik
    ],
    "florian.treptow@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
        "bbb393a8-bba5-4841-a1fc-9ae8ecfbd96f",  # Leitung F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "frank.adolf@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "frank.froese@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "frank.hornbostel@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "franziska.wehrheim@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "gabriele.kurzok@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "gesa-marie.fischer@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "bcd5573f-5e3a-4eb0-b51a-2119e595122f",  # Leitung Geschäftsführung Strategie
    ],
    "gisela.pietruska@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "greta.stuempel@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "15f7da41-c840-4fac-b403-701bc12742ad",  # Marketing
        "5292a75a-d977-4d4f-92e1-d3b633e3f0bf",  # Leitung Marketing
    ],
    "grit.heunemann@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "halil.kenan@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4773b7db-e4f9-4160-84be-2f06ee7b9937",  # Region Süd
    ],
    "heiko.preusser@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "henning.reich@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "holger.ritter@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "ina.hartmann@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "ingo.floerke@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "ismail.madrane@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "janine.butterbrod@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
        "3bb3a9f4-e9a8-4996-8992-ed88b0c54bc6",  # Leitung Export
    ],
    "jeanie.kaiser@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "516caf26-dcd1-4b45-a79d-283723e942aa",  # Controlling
    ],
    "jennifer.helmrich@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "jens.muench@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "jens.reichelt@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "45e877f2-8bdb-4361-84d4-becf067b255b",  # Leitung Informations- und Organisationsmanagement
    ],
    "jobst.klein@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "joerg.feilcke@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "jorrit.wolpers@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
    ],
    "julian.uhl@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4773b7db-e4f9-4160-84be-2f06ee7b9937",  # Region Süd
    ],
    "justus.meyer@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "jutta.teuber@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "kai.hemmerlein@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "karsten.brueckner@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "karsten.koch@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "kay.ibenthal@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "kerstin.loehmann@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "30e5d414-3ca8-4dfb-8201-a8a562e3a98c",  # Finanzen
    ],
    "kevin.rosenthal@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "khalid.aldughaim@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "konul.hidayatow@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "kora.fischer-kim@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
    ],
    "kristin.moehle@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "laila.nazari@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "lars.huntemann@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
        "178a5fc5-4b1e-45d4-af4f-9ce31f9a1547",  # Leitung Region West-Mitte
    ],
    "laura.villani@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "leonard.eisner@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "liseth.rodenberg@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
    ],
    "maj.demirezen@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "611550d4-4b39-451d-b906-208b03010ec2",  # Anlagenmanagement
    ],
    "marc.baum@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "marc.gasmus@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "marco.hirt@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "marco.klug@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "marco.sendner@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
        "db4157ed-2309-46f9-b9b9-8047f15014df",  # Leitung Global Key Account Management
    ],
    "marco.wendel@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "a9819947-2e92-490c-83af-a3735f64988f",  # Instandhaltung
        "b76a13cc-f0c4-494c-b343-feb8d2732dd1",  # Leitung Instandhaltung
    ],
    "marco.zint@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "marcus.amann@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "marcus.both@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "516caf26-dcd1-4b45-a79d-283723e942aa",  # Controlling
        "904bea85-0805-46ff-b146-ef36741d9d6e",  # Leitung Controlling
    ],
    "mareike.wendel@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "margret.burgdorf@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "maria.castelli@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "15f7da41-c840-4fac-b403-701bc12742ad",  # Marketing
    ],
    "mario.luebker@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "martin.bittner@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
        "e6e38901-fe70-489a-ada2-b61dfeb636ed",  # Leitung Zentrale Analytik
    ],
    "martin.gisa@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "martin.meyer@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "martin.zarski@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
    ],
    "matthias.otto@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "max.callegari@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "9fc8149d-85ee-4e50-b989-579d0909ba20",  # Leitung Technik
    ],
    "max.roesner@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "611550d4-4b39-451d-b906-208b03010ec2",  # Anlagenmanagement
        "280f8fdf-123b-49ba-8b19-cd5ff4eb7f79",  # Leitung Anlagenmanagement
    ],
    "melanie.lemke@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "melanie.menzel@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "516caf26-dcd1-4b45-a79d-283723e942aa",  # Controlling
    ],
    "melina.sander@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
    ],
    "melissa-sophie.bormke@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "michael.ertl@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "59c37098-5649-4b64-99e8-d7efc07e074d",  # Region Nord-Ost
    ],
    "michael.nadarzinski@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "michael.nickl@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "michael.pruefert@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "michael.schedler@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4773b7db-e4f9-4160-84be-2f06ee7b9937",  # Region Süd
    ],
    "michael.scheibner@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "86549184-0c24-4fb8-80b4-f317515a90de",  # Leitung Geschäftsführung CFO
    ],
    "miriam.schmikale@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "61d0adc6-033c-4649-bb1b-c589616eef58",  # Integriertes Management System
    ],
    "natalja.mainhardt@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "30444b8e-ccf1-4868-9d98-47320b03e12c",  # Tax management
    ],
    "nebojsa.obradovic@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "e8982280-291a-4913-a86e-fe4a5adf5c1a",  # Leitung Geschäftsführung (COO) Metalworking Europe
    ],
    "nick.markgraf@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "nicolas.ebel@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
    ],
    "nicolaus.dorn@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "019069a9-556a-4831-9ffb-76a502f47d49",  # F&E 1 Gießereitechnik
    ],
    "niklas.thiel@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "nikola.lazic@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "a9819947-2e92-490c-83af-a3735f64988f",  # Instandhaltung
    ],
    "nils.hammerschmidt@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "611550d4-4b39-451d-b906-208b03010ec2",  # Anlagenmanagement
    ],
    "ning.xu@fischerequity.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
    ],
    "norbert.keller@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "norman.gottschlich@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "nurcan.yapici@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "cb660fc0-9dce-4a9d-846b-2979beda2ee3",  # F&E 2 Wärmebehandlung
    ],
    "oeznur.mavigoek@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "516caf26-dcd1-4b45-a79d-283723e942aa",  # Controlling
    ],
    "olga.thiele@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "oliver.oest@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "pascal.coupechoux@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "patrick.kutzler@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
        "93cc8469-2dee-4f64-a707-43a579d0f310",  # Leitung Produktion
    ],
    "paul.geffert@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "paul.labocha@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "a9819947-2e92-490c-83af-a3735f64988f",  # Instandhaltung
    ],
    "petra.arndt@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "petra.halus@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "phil+testpetrofer@beyondtheloop.ai": [
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
        "15f7da41-c840-4fac-b403-701bc12742ad",  # Marketing
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
        "280f8fdf-123b-49ba-8b19-cd5ff4eb7f79",  # Leitung Anlagenmanagement
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
    ],
    "quentin.mayer@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
    ],
    "rafael.delcorralsanchez@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "ramon.linares@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "ramon.scheunert@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "f92903f4-1f5f-4c8b-8720-5a1153bdfacf",  # Export
    ],
    "rebecca.sauss@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "516caf26-dcd1-4b45-a79d-283723e942aa",  # Controlling
    ],
    "rene.bettels@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "b0d7510a-f0c2-4cb3-92af-5df3a82b7ac3",  # Global Key Account Management
    ],
    "rene.herzog@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "59c37098-5649-4b64-99e8-d7efc07e074d",  # Region Nord-Ost
        "5adc514e-11e2-4dc7-8fb0-6175fcda2d4c",  # Leitung Region Nord-Ost
    ],
    "ricardo.loges@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "a4e22785-779b-46ad-b07b-8c34939d0406",  # Technik
        "611550d4-4b39-451d-b906-208b03010ec2",  # Anlagenmanagement
    ],
    "rick.matthias@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "roberto.cagna@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "a7fb09b0-b131-4c56-9776-23cc7d33716b",  # Region West-Mitte
    ],
    "robin.strothotte@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "roger.altenburg@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "roland.guenther@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "roland.peters@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "019069a9-556a-4831-9ffb-76a502f47d49",  # F&E 1 Gießereitechnik
    ],
    "roman.lerich@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
    ],
    "ruediger.reichhardt@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "sabine.niele@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "sabine.rost@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "sandra.deister@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "sandra.greier@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
    ],
    "sascha.petsch@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "8b55cade-3b3d-4a17-8422-65c08fe085e7",  # Personalmanagement
    ],
    "scott.nicholson@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "sebastian.siemens@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "sibel.elmas@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
        "1c511479-d1f2-4ba7-9c45-0eef0e25acba",  # Leitung Einkauf
    ],
    "silke.bansemer@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "silvio.kraack@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "simon.scheunert@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "simone.fischer@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
    ],
    "sonja.zelazo@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "stefan.menzel@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8f9b6c68-5742-493e-8e3e-d5bc56bf2ac7",  # F&E 5 Industriereiniger und Korrosionsschutz
    ],
    "stefan.schettiger@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f48017b8-0e09-449c-8968-2e2b510154da",  # F&E 4 Zerspanung und Umformung
    ],
    "stefan.schindler@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "61d0adc6-033c-4649-bb1b-c589616eef58",  # Integriertes Management System
    ],
    "stefanie.gefroerer@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "30e5d414-3ca8-4dfb-8201-a8a562e3a98c",  # Finanzen
    ],
    "steffen.henkel@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "stephan.eberding@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
    ],
    "stephan.woiwode@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "susanne.finke@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "sven.ossenkop@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "416c83b7-3b6f-4cbe-8cf5-3e509bf6e9c4",  # Logistik
    ],
    "tabea.soencksen@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "f4e83e06-a218-45c7-8a86-575c76198915",  # Sicherheitsdatentechnik
    ],
    "tanja.kuhl@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "tanja.probst@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "30e5d414-3ca8-4dfb-8201-a8a562e3a98c",  # Finanzen
        "5fc2c0a2-d5a2-4bf2-af43-0afa5520468b",  # Leitung Finanzen
    ],
    "thomas.brandenburger@petrofer.com": [
        "e4a81f2b-7e38-4081-b163-1b3f7bc6db53",  # Geschäftsführung Strategie
        "b0757f1f-8c6d-4533-a461-2e8638c6eb52",  # Papierchemikalien
    ],
    "thomas.sobotta@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "8eba657b-f161-4441-905b-67cab7e8f387",  # F&E 3 Hydraulik und Schmierungstechnik Entwicklung
        "c421cdda-38c1-4cfd-8b58-82a68982abff",  # Leitung F&E 3 Hydraulik und Schmierungstechnik Entwicklung
    ],
    "thorsten.beitz@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "3e12a594-e449-4c75-866f-0fe0b73379b1",  # Produktmanagement
    ],
    "tim.kurbjoweit@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "timo.haefele@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4773b7db-e4f9-4160-84be-2f06ee7b9937",  # Region Süd
        "66a860cb-b0a6-4a3e-9c32-bcc3701ca0e1",  # Leitung Region Süd
    ],
    "timo.voegtel@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "e7eda362-2b2a-4793-ba99-e4662d0008a0",  # IT
    ],
    "tobias.arnold@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
        "e6e38901-fe70-489a-ada2-b61dfeb636ed",  # Leitung Zentrale Analytik
    ],
    "ulf.kussroll@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "2a72c5a7-7f39-4709-b7e5-f1174331e34f",  # Einkauf
    ],
    "ulrike.stuempel@petrofer.com": [
        "ca8a0340-baac-4da5-90ea-b96cf8e820a0",  # Geschäftsführung CFO
        "547ddddd-3143-4cf1-ac90-c3951028725e",  # Informations- und Organisationsmanagement
        "61d0adc6-033c-4649-bb1b-c589616eef58",  # Integriertes Management System
    ],
    "vefa.altinkilic@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
    ],
    "veronique.meyerhoff@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "d5751d2a-fbe1-48ad-be87-f28dde85e5ff",  # Forschung und Entwicklung
        "709907ec-7ce6-4552-b74e-ba3355c62120",  # Zentrale Analytik
    ],
    "volker.veit@petrofer.com": [
        "a40025e4-179e-49a7-821a-0d0249119748",  # Geschäftsführung CEO
        "2900fbdf-1db3-490d-a243-afc847cb3ca2",  # Produktion und Logistik
        "c7ce1b6b-05fb-4305-9d96-a2e91c65f25a",  # Produktion
    ],
    "yahya.elci@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "4a51362a-8f43-4540-b21a-6b9fd8ec41ec",  # Anwendungstechnik
    ],
    "yesim.atayer@petrofer.com": [
        "bf0cf044-8ab8-4e12-a758-88518b95d694",  # Geschäftsführung (COO) Metalworking Europe
        "03012285-b5d5-46a3-ac70-559676c24d7c",  # Vertrieb Metalworking Europe
        "01d40d0d-6ed9-46fc-aac3-ffa6ba8e357f",  # Innendienst
        "2ed25d80-606d-42e0-bff5-d890cbb4e082",  # Leitung Innendienst
    ],
}
