apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-env
  labels:
    {{- include "bchat.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "bchat.appConfigName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        name:
          regexp: "^{{ include "bchat.secretPrefix" . }}.+$"
      rewrite:
        - regexp:
            source: "^{{ include "bchat.secretPrefix" . }}(.+)$"
            target: "$1"
