{{- if .Values.app.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app
  labels:
    {{- include "bchat.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.app.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "bchat.appSelector" . | nindent 6 }}
{{- end }}
