"""Postgres migration adjustments

Revision ID: 002
Revises: 001
Create Date: 2025-12-22 10:07:00.493296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            ALTER TABLE "auth" ALTER COLUMN "active" TYPE boolean USING "active" = 1;
        """)
    )

    conn.execute(
        sa.text("""
            ALTER TABLE "chat" ALTER COLUMN "archived" TYPE boolean USING "archived" = 1;
        """)
    )

    conn.execute(
        sa.text("""
            ALTER TABLE prompt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        """)
    )

    conn.execute(
        sa.text("""
            ALTER TABLE config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        """)
    )

    conn.execute(
        sa.text("""
            TRUNCATE TABLE model_cost;
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Perplexity Sonar Pro', 3, 15, null, null, null, null, 10);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Perplexity Sonar Deep Research', 2, 8, null, null, null, 3, 5);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Perplexity Sonar Reasoning Pro', 2, 8, null, null, null, null, 10);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Mistral Large 2', 2, 6, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('text-embedding-3-small', 0.02, null, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('flux-kontext-max', null, null, 0.04, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('tts-1', null, null, null, null, 15, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('whisper-1', null, null, null, 0.006, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Google 2.5 Flash', 0.15, 0.6, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Google 2.5 Pro', 1.25, 10, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT o3', 2, 8, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT o4-mini', 1.1, 4.4, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Grok 4', 3, 15, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT-5', 1.25, 10, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Claude 4.5 Haiku', 1, 5, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('Claude Sonnet 4.5', 3, 15, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT-5 mini', 0.25, 2, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT-5 nano', 0.05, 0.4, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT-5.1 instant', 1.25, 10, null, null, null, null, null);
            INSERT INTO model_cost (model_name, cost_per_million_input_tokens, cost_per_million_output_tokens, cost_per_image, cost_per_minute, cost_per_million_characters, cost_per_million_reasoning_tokens, cost_per_thousand_search_queries) VALUES ('GPT-5.1 thinking', 1.25, 10, null, null, null, null, null);
        """)
    )



def downgrade() -> None:
    pass
